[data.PlantExpertVQA]
data_path= PlantExpertVQA/data
train_file= train.csv
test_file= test.csv
validation_file= val.csv

text_columns= question_text, answer
columns_to_remove= dataset_source

[data.PlantExpertVQA.na_fill]
answer_type= unspecified
question_text=    ; blank string
question_category= unspecified
cognitive_level= unspecified

[logging]
; options: DEBUG, INFO, WARNING, ERROR, CRITICAL
level= DEBUG
pattern= %%(log_color)s%%(asctime)s [%%(levelname)-8s]: %%(message)s%%(reset)s

[logging.colors]
DEBUG = cyan
INFO = black
WARNING = yellow
ERROR = red
CRITICAL = bold_red